from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

import pandas as pd


HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Optimization Report</title>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<style>
  :root {{
    --bg: #0b0f14;
    --fg: #c7d1db;
    --muted: #9aa7b3;
    --card: #121821;
    --green: #38d39f;
    --red: #f87171;
  }}
  html, body {{ background: var(--bg); color: var(--fg); font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Inter, "Helvetica Neue", Arial, "Apple Color Emoji", "Segoe UI Emoji"; }}
  .wrap {{ max-width: 1200px; margin: 32px auto; padding: 0 16px; }}
  h1, h2, h3 {{ color: #e6edf3; }}
  .grid {{ display: grid; gap: 12px; grid-template-columns: repeat(12, 1fr); }}
  .card {{ background: var(--card); border-radius: 14px; padding: 16px 18px; }}
  .span-12 {{ grid-column: span 12; }}
  .span-6 {{ grid-column: span 6; }}
  .span-4 {{ grid-column: span 4; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 14px; }}
  th, td {{ text-align: right; padding: 6px 8px; border-bottom: 1px solid rgba(255,255,255,0.05); }}
  th:first-child, td:first-child {{ text-align: left; }}
  tr:hover td {{ background: rgba(255,255,255,0.02); }}
  .muted {{ color: var(--muted); font-size: 12px; }}
  .kpi {{ font-size: 20px; font-weight: 700; color: var(--green); }}
  .neg {{ color: var(--red); }}
</style>
</head>
<body>
<div class="wrap">
  <h1>Optimization Report</h1>
  <div class="grid">
    <div class="card span-12">
      <h2>Summary</h2>
      <div id="summary"></div>
      <div class="muted">Generated by tradinng-bot</div>
    </div>

    <div class="card span-6">
      <h3>Sweep (top rows)</h3>
      {sweep_table}
    </div>

    <div class="card span-6">
      <h3>Ranked (top rows)</h3>
      {ranked_table}
    </div>

    <div class="card span-12">
      <h3>Walk-Forward (per-config means)</h3>
      {wf_table}
    </div>

    <div class="card span-12">
      <h3>Final Backtest</h3>
      <pre>{final_json}</pre>
    </div>
  </div>
</div>
<script>
  const summary = {summary_json};
  document.getElementById("summary").innerText = JSON.stringify(summary, null, 2);
</script>
</body>
</html>
"""


def _df_to_html(path: Optional[Path], n: int = 20) -> str:
    if not path:
        return "<em>No file</em>"
    p = Path(path)
    if not p.exists():
        return f"<em>Missing: {p}</em>"
    try:
        df = pd.read_csv(p)
    except Exception as e:
        return f"<em>Failed to read {p.name}: {e}</em>"
    if df.empty:
        return "<em>Empty</em>"
    return df.head(n).to_html(index=False)


def write_html(
    output_html: Path,
    *,
    summary_json: dict,
    sweep_csv: Optional[Path],
    ranked_csv: Optional[Path],
    wf_csv: Optional[Path],
    final_metrics: Optional[dict],
) -> Path:
    output_html = Path(output_html)
    output_html.parent.mkdir(parents=True, exist_ok=True)

    html = HTML_TEMPLATE.format(
        sweep_table=_df_to_html(sweep_csv),
        ranked_table=_df_to_html(ranked_csv),
        wf_table=_df_to_html(wf_csv),
        summary_json=json.dumps(summary_json, ensure_ascii=False),
        final_json=json.dumps(final_metrics or {}, ensure_ascii=False, indent=2),
    )
    output_html.write_text(html, encoding="utf-8")
    return output_html
